server:
  port: 8083
spring:
  application:
    name: notification-service
    cloud:
      consul:
        discovery:
          instanceId: ${spring.application.name}:${random.value}
  datasource:
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5448/postgres
    username: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
  hibernate:
    ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.mail.ru
    port: 587
    username: microservices.mp
    password: m2P3taauSAY(
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#custom properties
rabbitmq:
  host: localhost
  nutrition:
    queue: nutritionProgramsQueue
  user:
    queue: userEventsQueue
clients:
  user-service:
    url: http://localhost:8080