version: '3.5'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5448:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"